//
// Created by Pfifer, Justin on 3/7/17.
//

#ifndef AMAZON_KINESIS_PRODUCER_INTERNAL_BUILD_INFO_H
#define AMAZON_KINESIS_PRODUCER_INTERNAL_BUILD_INFO_H

#define BUILD_VERSION_XSTR(x) BUILD_VERSION_STR(x)
#define BUILD_VERSION_STR(x) #x
#define BUILD_VERSION BUILD_VERSION_XSTR(COMMIT_DATA)

#endif //AMAZON_KINESIS_PRODUCER_INTERNAL_BUILD_INFO_H
